import { Button, Code, Heading, Text } from '@chakra-ui/react';
import Head from 'next/head'
import { useAuth } from '@/lib/auth'

export default function Home() {
  const { user, signinWithGitHub, signout } = useAuth();
  
  return (
    <div>
      <Head>
        <title>fastlu feedback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Heading fontWeight={700}>Fastly feedback</Heading>
        <Text>
          Currenct user: <Code>{ user?.email ?? 'None' }</Code>
        </Text>
        { user 
          ? <Button onClick={signout}>Sign out</Button> 
          : <Button onClick={signinWithGitHub}>Sign in</Button> 
        }
      </main>
    </div>
  )
}
